//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.CryptoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CryptoStr", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CryptoStr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceString {
            get {
                return this.SourceStringField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceStringField, value) != true)) {
                    this.SourceStringField = value;
                    this.RaisePropertyChanged("SourceString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CryptoServiceReference.CryptoServiceSoap")]
    public interface CryptoServiceSoap {
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Encrypt", ReplyAction="*")]
        ServiceClient.CryptoServiceReference.EncryptResponse Encrypt(ServiceClient.CryptoServiceReference.EncryptRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Decrypt", ReplyAction="*")]
        ServiceClient.CryptoServiceReference.DecryptResponse Decrypt(ServiceClient.CryptoServiceReference.DecryptRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Encrypt", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference.EncryptRequestBody Body;
        
        public EncryptRequest() {
        }
        
        public EncryptRequest(ServiceClient.CryptoServiceReference.EncryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference.CryptoStr str;
        
        public EncryptRequestBody() {
        }
        
        public EncryptRequestBody(ServiceClient.CryptoServiceReference.CryptoStr str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference.EncryptResponseBody Body;
        
        public EncryptResponse() {
        }
        
        public EncryptResponse(ServiceClient.CryptoServiceReference.EncryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference.CryptoStr EncryptResult;
        
        public EncryptResponseBody() {
        }
        
        public EncryptResponseBody(ServiceClient.CryptoServiceReference.CryptoStr EncryptResult) {
            this.EncryptResult = EncryptResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Decrypt", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference.DecryptRequestBody Body;
        
        public DecryptRequest() {
        }
        
        public DecryptRequest(ServiceClient.CryptoServiceReference.DecryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DecryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference.CryptoStr str;
        
        public DecryptRequestBody() {
        }
        
        public DecryptRequestBody(ServiceClient.CryptoServiceReference.CryptoStr str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceClient.CryptoServiceReference.DecryptResponseBody Body;
        
        public DecryptResponse() {
        }
        
        public DecryptResponse(ServiceClient.CryptoServiceReference.DecryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DecryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.CryptoServiceReference.CryptoStr DecryptResult;
        
        public DecryptResponseBody() {
        }
        
        public DecryptResponseBody(ServiceClient.CryptoServiceReference.CryptoStr DecryptResult) {
            this.DecryptResult = DecryptResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CryptoServiceSoapChannel : ServiceClient.CryptoServiceReference.CryptoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CryptoServiceSoapClient : System.ServiceModel.ClientBase<ServiceClient.CryptoServiceReference.CryptoServiceSoap>, ServiceClient.CryptoServiceReference.CryptoServiceSoap {
        
        public CryptoServiceSoapClient() {
        }
        
        public CryptoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CryptoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CryptoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CryptoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.CryptoServiceReference.EncryptResponse ServiceClient.CryptoServiceReference.CryptoServiceSoap.Encrypt(ServiceClient.CryptoServiceReference.EncryptRequest request) {
            return base.Channel.Encrypt(request);
        }
        
        public ServiceClient.CryptoServiceReference.CryptoStr Encrypt(ServiceClient.CryptoServiceReference.CryptoStr str) {
            ServiceClient.CryptoServiceReference.EncryptRequest inValue = new ServiceClient.CryptoServiceReference.EncryptRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference.EncryptRequestBody();
            inValue.Body.str = str;
            ServiceClient.CryptoServiceReference.EncryptResponse retVal = ((ServiceClient.CryptoServiceReference.CryptoServiceSoap)(this)).Encrypt(inValue);
            return retVal.Body.EncryptResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceClient.CryptoServiceReference.DecryptResponse ServiceClient.CryptoServiceReference.CryptoServiceSoap.Decrypt(ServiceClient.CryptoServiceReference.DecryptRequest request) {
            return base.Channel.Decrypt(request);
        }
        
        public ServiceClient.CryptoServiceReference.CryptoStr Decrypt(ServiceClient.CryptoServiceReference.CryptoStr str) {
            ServiceClient.CryptoServiceReference.DecryptRequest inValue = new ServiceClient.CryptoServiceReference.DecryptRequest();
            inValue.Body = new ServiceClient.CryptoServiceReference.DecryptRequestBody();
            inValue.Body.str = str;
            ServiceClient.CryptoServiceReference.DecryptResponse retVal = ((ServiceClient.CryptoServiceReference.CryptoServiceSoap)(this)).Decrypt(inValue);
            return retVal.Body.DecryptResult;
        }
    }
}
