//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceClient.CyptoWCFServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CryptoStr", Namespace="http://schemas.datacontract.org/2004/07/NewWcfService")]
    [System.SerializableAttribute()]
    public partial class CryptoStr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceString {
            get {
                return this.SourceStringField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceStringField, value) != true)) {
                    this.SourceStringField = value;
                    this.RaisePropertyChanged("SourceString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CyptoWCFServiceReference.ICyptoWCFService")]
    public interface ICyptoWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICyptoWCFService/Encrypt", ReplyAction="http://tempuri.org/ICyptoWCFService/EncryptResponse")]
        WCFServiceClient.CyptoWCFServiceReference.CryptoStr Encrypt(WCFServiceClient.CyptoWCFServiceReference.CryptoStr str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICyptoWCFService/Decrypt", ReplyAction="http://tempuri.org/ICyptoWCFService/DecryptResponse")]
        WCFServiceClient.CyptoWCFServiceReference.CryptoStr Decrypt(WCFServiceClient.CyptoWCFServiceReference.CryptoStr str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICyptoWCFServiceChannel : WCFServiceClient.CyptoWCFServiceReference.ICyptoWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CyptoWCFServiceClient : System.ServiceModel.ClientBase<WCFServiceClient.CyptoWCFServiceReference.ICyptoWCFService>, WCFServiceClient.CyptoWCFServiceReference.ICyptoWCFService {
        
        public CyptoWCFServiceClient() {
        }
        
        public CyptoWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CyptoWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CyptoWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CyptoWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFServiceClient.CyptoWCFServiceReference.CryptoStr Encrypt(WCFServiceClient.CyptoWCFServiceReference.CryptoStr str) {
            return base.Channel.Encrypt(str);
        }
        
        public WCFServiceClient.CyptoWCFServiceReference.CryptoStr Decrypt(WCFServiceClient.CyptoWCFServiceReference.CryptoStr str) {
            return base.Channel.Decrypt(str);
        }
    }
}
