{
 "title": "Cluster3 work",
 "time": { "from": "2019-01-01T03:07:30.000Z", "to": "2019-02-02T20:37:30.000Z" },
 "panels": [
  {
   "title": "Минимумы по дням",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Минимальное по дням (1 давление)",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT min(\"pressure1\") FROM \"cluster3\" GROUP BY time(24h) fill(\"none\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Минимальное по дням (2 давление)",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT min(\"pressure2\") FROM \"cluster3\" GROUP BY time(24h) fill(\"none\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Минимальное по дням (3 давление)",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT min(\"pressure3\") FROM \"cluster3\" GROUP BY time(24h) fill(\"none\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Минимальное по дням (4 давление)",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT min(\"pressure4\") FROM \"cluster3\" GROUP BY time(24h) fill(\"none\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Минимальное по дням (5 давление)",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT min(\"pressure5\") FROM \"cluster3\" GROUP BY time(24h) fill(\"none\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Минимум",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Минимальное (1)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT min(\"pressure1\") FROM \"cluster3\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Минимальное (2)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT min(\"pressure2\") FROM \"cluster3\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Минимальное (3)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT min(\"pressure3\") FROM \"cluster3\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Минимальное (4)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT min(\"pressure4\") FROM \"cluster3\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Минимальное (5)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT min(\"pressure5\") FROM \"cluster3\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "cluster3",
   "type": "graph",
   "gridPos": { "h": 14, "w": 7, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT * FROM \"cluster3\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Хольт Винтерс",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select HOLT_WINTERS(first(/pressure/),72,72) from cluster3 group by time(1h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Время работы",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Время работы",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"pressure5\")/mean(\"pressure5\")*15 FROM \"cluster3\" WHERE (\"pressure5\" > 7) GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Время простоя",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"pressure5\")/mean(\"pressure5\")*15 FROM \"cluster3\" WHERE (\"pressure5\" < 7) GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Максимумы по дням",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Максимальное по дням (1 давление)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"pressure1\") FROM \"cluster3\" GROUP BY time(24h) fill(\"none\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Максимальное по дням (2 давление)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"pressure2\") FROM \"cluster3\" GROUP BY time(24h) fill(\"none\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Максимальное по дням (3 давление)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"pressure3\") FROM \"cluster3\" GROUP BY time(24h) fill(\"none\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Максимальное по дням (4 давление)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"pressure4\") FROM \"cluster3\" GROUP BY time(24h) fill(\"none\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Максимальное по дням (5 давление)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"pressure5\") FROM \"cluster3\" GROUP BY time(24h) fill(\"none\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Максимум",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Максимальное (1)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"pressure1\") FROM \"cluster3\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Максимальное (2)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"pressure2\") FROM \"cluster3\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Максимальное (3)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"pressure3\") FROM \"cluster3\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Максимальное (4)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"pressure4\") FROM \"cluster3\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Максимальное (5)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"pressure5\") FROM \"cluster3\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Плавающая средняя по дням",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Среднее по 4 давлению",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pressure4\") FROM \"cluster3\" WHERE (\"time\" >= '2019-01-01 00:00:00') GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Среднее по 5 давлению",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pressure5\") FROM \"cluster3\" WHERE (\"time\" >= '2019-01-01 00:00:00') GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Разница среднесуточных значений",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(pressure1)-mean(pressure2) from cluster3 group by time(24h) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Средние по дням",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "Среднее по дням (1 давление)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pressure1\") FROM \"cluster3\" GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Среднее по дням (2 давление)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pressure2\") FROM \"cluster3\" GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Среднее по дням (3 давление)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pressure3\") FROM \"cluster3\" GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Среднее по дням (4 давление)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pressure4\") FROM \"cluster3\" GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Среднее по дням (5 давление)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pressure5\") FROM \"cluster3\" GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Средние значения",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Среднее (1)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT mean(\"pressure1\") FROM \"cluster3\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Среднее (2)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT mean(\"pressure2\") FROM \"cluster3\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Среднее (3)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT mean(\"pressure3\") FROM \"cluster3\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Среднее (4)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT mean(\"pressure4\") FROM \"cluster3\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Среднее (5)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster3",
     "query": "SELECT mean(\"pressure5\") FROM \"cluster3\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}